apiVersion: v1
kind: ConfigMap
metadata:
  name: orchestapi-config
  labels:
    app.kubernetes.io/name: orchestapi
    app.kubernetes.io/component: application
data:
  SPRING_PROFILES_ACTIVE: prod
  SERVER_PORT: "8080"
  CONTEXT_PATH: /orchestapi
  JAVA_OPTS: -XX:+UseContainerSupport -XX:MaxRAMPercentage=75.0
