apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: orchestapi-internal

resources:
  - ../../base

images:
  - name: orchestapi
    newName: registry-stg.vestack.sbuxcf.net/agent-develop-lifecycle-management/orchestapi
    newTag: replace-me
